import type { Tool } from './types';

const imageAccept = '.jpg,.jpeg,.png,.webp,.heic,.heif,.avif';
export const tools: Tool[] = [
  {
    id: 'compress-image',
    title: 'Image compressor',
    nav: 'Compress image',
    group: 'Images',
    accept: imageAccept,
    multiple: true,
    action: 'Compress images',
    description: 'Reduce image file sizes to a requested KB limit with batch downloads.',
  },
  {
    id: 'resize-image',
    title: 'Resize & crop image',
    nav: 'Resize & crop',
    group: 'Images',
    accept: imageAccept,
    multiple: true,
    action: 'Export images',
    description: 'Resize images to exact dimensions or crop them before exporting.',
  },
  {
    id: 'heic-to-jpg',
    title: 'HEIC converter',
    nav: 'HEIC to JPG',
    group: 'Images',
    accept: '.heic,.heif',
    multiple: true,
    action: 'Convert images',
    description: 'Convert HEIC and HEIF photos into JPG or PNG files.',
  },
  {
    id: 'webp-converter',
    title: 'WebP converter',
    nav: 'WebP converter',
    group: 'Images',
    accept: imageAccept,
    multiple: true,
    action: 'Convert images',
    description: 'Convert WebP to JPG or PNG, or create WebP images from other formats.',
  },
  {
    id: 'photo-signature',
    title: 'Photo & signature prep',
    nav: 'Photo & signature',
    group: 'Images',
    accept: imageAccept,
    multiple: false,
    action: 'Prepare image',
    description: 'Prepare photos and signature images for upload dimensions and file-size limits.',
  },
  {
    id: 'jpg-to-pdf',
    title: 'Images to PDF',
    nav: 'JPG / PNG to PDF',
    group: 'PDFs',
    accept: imageAccept,
    multiple: true,
    action: 'Create PDF',
    description: 'Arrange JPG and PNG images into a PDF with custom page sizes.',
  },
  {
    id: 'merge-pdf',
    title: 'Merge PDFs',
    nav: 'Merge PDF',
    group: 'PDFs',
    accept: '.pdf',
    multiple: true,
    action: 'Merge PDFs',
    description: 'Combine PDFs with page previews and custom ordering.',
  },
  {
    id: 'split-pdf',
    title: 'Split PDF',
    nav: 'Split PDF',
    group: 'PDFs',
    accept: '.pdf',
    multiple: false,
    action: 'Split PDF',
    description: 'Extract PDF page ranges or download each page separately.',
  },
  {
    id: 'organize-pdf',
    title: 'Organize PDF',
    nav: 'Rotate & reorder',
    group: 'PDFs',
    accept: '.pdf',
    multiple: false,
    action: 'Save PDF',
    description: 'Rotate, reorder, and remove PDF pages before downloading.',
  },
  {
    id: 'sign-pdf',
    title: 'Sign & annotate PDF',
    nav: 'Signature & text',
    group: 'PDFs',
    accept: '.pdf',
    multiple: false,
    action: 'Save signed PDF',
    description: 'Add a visible drawn signature and text to a PDF.',
  },
  {
    id: 'docx-to-markdown',
    title: 'Word to Markdown',
    nav: 'DOCX to Markdown',
    group: 'Documents',
    accept: '.docx',
    multiple: false,
    action: 'Convert document',
    description: 'Convert DOCX documents to Markdown with tables and bundled images.',
  },
  {
    id: 'markdown-to-pdf',
    title: 'Markdown to PDF',
    nav: 'Markdown to PDF',
    group: 'Documents',
    accept: '.md,.markdown,.txt',
    multiple: false,
    action: 'Export PDF',
    description: 'Export Markdown with headings, lists, tables, and code as a selectable-text PDF.',
  },
];
export const getTool = (id?: string) => tools.find((tool) => tool.id === id);
